### PR TITLE
Improve new joint initialization function: keep rotation values between 0º and 360º

### PR DESCRIPTION
**Pull request by piratesephiroth**
Workaround for ruby's dynamic typing.

### CODE REVIEW

**Comment by piratesephiroth** [comment]
After that we just have to fix the rotation direction for the joints when we're building the animation tracks.

something like 

```
loop through joint changes for this specific joint
{
    previousRotation = rotation;
    rotation = current joint rotation

    if (key_frame > 0)
    {
        difference = rotation - previousRotation;
        
        if (difference > 32768)
        {
            rotation -= 65536;
        }
        else if (difference < -32768)
        {
            rotation += 65536;
        }
    }

    rotationInDegrees = rotation / 182.0

}

https://user-images.githubusercontent.com/10672233/117592124-cc95e980-b10d-11eb-9a11-7c1761238c61.mp4

**Comment by LagoLunatic** [comment]
Tried it out and I don't think this is correct lol
image

**Comment by LagoLunatic** [comment]
What program is that output.mp4 from? Doesn't look like Spriter.

**Comment by piratesephiroth** [comment]
> What program is that output.mp4 from? Doesn't look like Spriter.

ah that's the Godot engine

**Comment by LagoLunatic** [comment]
> ah that's the Godot engine

Oh I thought it looked familiar... so is your `initialize_joint_states_new` intended as an export function for Godot and it doesn't work with anything else? Since it looks broken in both DSVEdit and Spriter. I'm wondering why your mp4 is correct looking.

**Comment by piratesephiroth** [comment]
> > ah that's the Godot engine
> 
> Oh I thought it looked familiar... so is your `initialize_joint_states_new` intended as an export function for Godot and it doesn't work with anything else? Since it looks broken in both DSVEdit and Spriter. I'm wondering why your mp4 is correct looking.

yeah, that's why I added the "new" suffix, because it wasn't supposed to replace the old one yet...

**Pull request merged**
